import type { Post } from "@/types";

export const CATEGORIES = ["All", "SEO", "AI", "Engineering", "Product", "Marketing", "Case Studies", "News"];

export const POSTS: Post[] = [
  {
    slug: "aeo-guide-2026",
    title: "The 2026 guide to AEO for Indian brands",
    excerpt: "Answer Engine Optimization is replacing the first page of Google. The complete playbook for winning AI answers in India.",
    category: "AI",
    author: "Kavya Rao",
    initials: "KR",
    date: "Jun 28, 2026",
    readTime: "12 min",
    featured: true,
    thumb: "from-orange-100 via-amber-50 to-white",
    content: [
      "A growing share of buying research in India now starts inside ChatGPT, Perplexity, or Google's AI Overviews instead of a traditional search box. That shift changes what \"visibility\" means for a brand: it's no longer just about ranking a page, it's about being the answer an AI assistant chooses to give.",
      "Answer Engine Optimization (AEO) is the practice of structuring your brand's information, content, and technical setup so that AI systems can reliably find, understand, and cite you. It borrows some habits from traditional SEO — clear content, credible sources, structured data — but the target audience is a language model reading and synthesizing text, not a person scanning ten blue links.",
      "For Indian brands specifically, three things matter more than global playbooks acknowledge: the language your customers actually type in (Hindi, Hinglish, and regional languages, not just English), the platforms they actually use (WhatsApp and marketplace assistants alongside ChatGPT), and realistic budgets that don't assume a US enterprise marketing spend.",
      "Start with the basics: make sure your site has clean schema markup (Organization, Product, FAQPage), a clear and consistent brand description across your own site and third-party listings, and genuinely useful content that answers the exact questions your customers ask an AI assistant. Then track it — you can't improve what you don't measure.",
    ],
  },
  {
    slug: "lumora-hindi-prompts",
    title: "How Lumora won 7 Hindi money prompts in 60 days",
    excerpt: "A D2C skincare brand went from invisible to ChatGPT's top recommendation — in the language its customers actually use.",
    category: "Case Studies",
    author: "Dev Malhotra",
    initials: "DM",
    date: "Jun 21, 2026",
    readTime: "8 min",
    featured: true,
    thumb: "from-stone-100 via-orange-50 to-white",
    content: [
      "Lumora Skincare had a familiar problem: strong English-language SEO, and almost no presence when Indian customers asked AI assistants in Hindi — prompts like \"sabse accha face wash kaunsa hai\" simply never surfaced the brand.",
      "The team started by auditing what ChatGPT and Gemini actually said in response to their ten highest-intent Hindi and Hinglish prompts. In the first pass, Lumora was mentioned in exactly zero of them — competitors with weaker products but clearer, better-structured Hindi content were winning every one.",
      "Over the next 60 days, the team rewrote key product pages with genuinely native Hindi and Hinglish phrasing (not machine-translated English), added FAQ schema answering the exact questions customers were asking AI assistants, and built a handful of citation-worthy comparison pages.",
      "The result: Lumora went from being mentioned in 0 of 10 tracked Hindi prompts to 7 of 10, including becoming ChatGPT's top recommendation for its core \"best face wash\" category query. AI-driven traffic became a measurable, zero-ad-spend acquisition channel within the quarter.",
    ],
  },
  {
    slug: "llms-txt-explained",
    title: "llms.txt, explained in plain English",
    excerpt: "What the new crawler standard means for your site, and how to ship one in ten minutes.",
    category: "SEO",
    author: "Kavya Rao",
    initials: "KR",
    date: "Jun 14, 2026",
    readTime: "6 min",
    thumb: "from-amber-50 to-white",
    content: [
      "llms.txt is a proposed standard, similar in spirit to robots.txt, that gives AI crawlers and assistants a clean, structured summary of what your site is and which pages matter most — instead of forcing them to guess from a messy sitemap or heavy JavaScript rendering.",
      "It lives at the root of your domain (yourdomain.com/llms.txt) as a plain Markdown file listing your site's purpose, key pages, and short descriptions of each. Think of it as a one-page briefing document written for a language model instead of a human visitor.",
      "It won't magically guarantee citations — no file can do that — but it removes friction for AI crawlers that do respect it, and it's a five-minute technical fix with essentially no downside. Pair it with clean schema markup and clear content, and you've covered the table-stakes technical layer of AEO.",
      "Practically: list your 10-20 most important pages, write one honest sentence about what each one covers, and keep the file updated as your site changes. Treat it the same way you'd treat a sitemap — small effort, cheap insurance.",
    ],
  },
  {
    slug: "hinglish-prompts-chatgpt",
    title: "Why Hinglish prompts behave differently in ChatGPT",
    excerpt: "Machine-translated prompts miss how India actually asks. What our native-language runs reveal.",
    category: "AI",
    author: "Ishaan Verma",
    initials: "IV",
    date: "Jun 7, 2026",
    readTime: "9 min",
    thumb: "from-orange-50 to-white",
    content: [
      "A common mistake in early AEO efforts is treating Hinglish as \"Hindi that happens to use English letters.\" In practice, Hinglish prompts carry their own grammar, code-switching patterns, and phrasing habits that a straight English-to-Hindi translation doesn't capture.",
      "When we compared machine-translated Hindi prompts against genuinely native-written Hinglish prompts for the same underlying question, the AI responses differed meaningfully — different brands got mentioned, different sources got cited, and sentiment sometimes shifted.",
      "The practical implication for tracking: if your AEO tool only translates English prompts into Hindi programmatically, you're measuring a version of the question real customers rarely ask. Native-speaker-written prompts, reviewed for how people actually type when talking to an AI assistant, produce meaningfully more accurate visibility data.",
      "This is also why content strategy needs the same care — content written to match how customers actually phrase questions outperforms content that's merely translated from an English original.",
    ],
  },
  {
    slug: "nightly-visibility-pipeline",
    title: "Inside our nightly visibility pipeline",
    excerpt: "Batch APIs, deduplication and cost ceilings: how 12,000 prompts run every night without melting the budget.",
    category: "Engineering",
    author: "Dev Malhotra",
    initials: "DM",
    date: "May 30, 2026",
    readTime: "11 min",
    thumb: "from-stone-100 to-white",
    content: [
      "Running thousands of prompts across multiple AI engines every night is fundamentally a cost-and-scheduling problem before it's an AI problem. The interesting engineering work isn't calling an LLM API — it's calling it efficiently, thousands of times, without your bill or your reliability falling apart.",
      "Our pipeline batches scheduled runs through providers' async/batch endpoints wherever available, since real-time responsiveness doesn't matter for a check that runs once a day. That alone meaningfully cuts cost versus calling the standard real-time endpoint for every single prompt.",
      "We also segment prompts by volatility: high-priority, competitive prompts get checked daily, while long-tail prompts refresh weekly. This single decision cuts total run volume substantially with minimal loss of insight, since long-tail visibility rarely swings day to day.",
      "Every run logs its token usage and cost against the specific brand and prompt it served, which lets us see gross margin per customer clearly — a step a lot of early tools in this category reportedly skipped, to their later regret.",
    ],
  },
  {
    slug: "introducing-auto-fix",
    title: "Introducing Auto-Fix: from gap to deploy in one click",
    excerpt: "We stopped telling you what to fix and started fixing it. Schema, content and CMS pushes, reviewed by you.",
    category: "Product",
    author: "Kavya Rao",
    initials: "KR",
    date: "May 22, 2026",
    readTime: "5 min",
    thumb: "from-orange-100 to-white",
    content: [
      "The most common frustration with AI visibility tools isn't the data — it's the gap between \"here's what's wrong\" and actually fixing it. Most dashboards stop at diagnosis and leave the work to you.",
      "Auto-Fix closes that gap. When we detect a visibility gap — missing schema markup, a thin page, an unanswered high-intent prompt — we draft the actual fix: the schema code, or a full content draft, ready to review.",
      "Nothing publishes without your explicit approval. Every draft is clearly labeled and sits in a review queue until a real person signs off, then it can be pushed straight to WordPress or Shopify in one click.",
      "This isn't just a convenience feature — it's a deliberate design choice that keeps AI-assisted content safely inside the editorial standards that keep sites healthy long-term.",
    ],
  },
  {
    slug: "cfo-ready-aeo-reports",
    title: "AEO reporting your CFO will actually read",
    excerpt: "Visibility scores don't unlock budget. Revenue attribution does. A template that works.",
    category: "Marketing",
    author: "Ishaan Verma",
    initials: "IV",
    date: "May 15, 2026",
    readTime: "7 min",
    thumb: "from-amber-50 via-orange-50 to-white",
    content: [
      "A visibility score is a useful internal metric, but it rarely survives contact with a CFO or a founder who wants to know one thing: did this make us money?",
      "The reporting template that actually works ties AI visibility to sessions, then sessions to orders or leads, then orders to revenue — the same chain any performance marketing channel has to prove itself against.",
      "In practice, that means connecting your visibility tool to GA4 and your commerce platform (Shopify, WooCommerce, Razorpay) so you can say, concretely, \"AI search sent us X sessions this month, which converted to ₹Y in revenue\" — not just \"our score went up 8 points.\"",
      "Lead with the revenue number, use the visibility score as supporting detail, and you'll have a much easier time defending — and growing — the budget for this work.",
    ],
  },
  {
    slug: "meridian-white-label",
    title: "How Meridian pitches with white-label audits",
    excerpt: "One agency's playbook for turning free visibility audits into 12 signed retainers.",
    category: "Case Studies",
    author: "Dev Malhotra",
    initials: "DM",
    date: "May 8, 2026",
    readTime: "8 min",
    thumb: "from-stone-100 via-amber-50 to-white",
    content: [
      "Meridian Digital, a mid-sized Indian agency, was struggling to explain AEO to prospective clients in the abstract. Numbers and jargon didn't land — a concrete, branded example did.",
      "Their fix: generate a free, lite AI-visibility audit for each prospect before the first sales call, using nothing but the prospect's public domain name — no site access required. The audit showed exactly which prompts the prospect was losing, and to whom.",
      "Walking into a pitch with the prospect's own data, branded with Meridian's logo, changed the conversation from \"what is AEO?\" to \"how fast can you fix this?\" — a materially easier sale.",
      "Over one quarter, this single tactic converted into 12 signed retainer clients, turning AEO from a hard-to-explain add-on into Meridian's most requested new service line.",
    ],
  },
  {
    slug: "gemini-shopping-answers",
    title: "Gemini's new shopping answers: what changed",
    excerpt: "Google's AI shopping surfaces are rolling out in India. Here's what we're seeing in the data.",
    category: "News",
    author: "Kavya Rao",
    initials: "KR",
    date: "May 1, 2026",
    readTime: "4 min",
    thumb: "from-orange-50 via-white to-white",
    content: [
      "Google has continued expanding AI-driven shopping answers inside Gemini and AI Overviews, surfacing product recommendations, comparisons, and pricing summaries directly in response to shopping-intent queries — increasingly in India, including in Hindi.",
      "For brands, this means a growing share of \"best [product] in India\" style queries may never reach a traditional results page at all — the AI-generated answer becomes the entire experience for that search.",
      "Early observations suggest structured product data (schema markup, clear pricing, availability) meaningfully improves whether a brand appears in these AI-generated shopping summaries, echoing the same technical fundamentals that matter across every AI engine.",
      "We'll keep tracking how this surface evolves in the Indian market specifically, since Google's rollout pace and behavior can differ meaningfully by region and language.",
    ],
  },
  {
    slug: "faq-schema-citations",
    title: "FAQ schema that actually gets cited",
    excerpt: "Most FAQ markup is ignored by answer engines. The patterns that earn citations, with examples.",
    category: "SEO",
    author: "Ishaan Verma",
    initials: "IV",
    date: "Apr 24, 2026",
    readTime: "6 min",
    thumb: "from-amber-100 to-white",
    content: [
      "FAQ schema is one of the most commonly implemented — and most commonly wasted — pieces of structured data. Many sites add generic, marketing-flavored questions that no real customer, or AI assistant, would ever actually ask.",
      "The FAQ blocks that earn citations tend to mirror the exact phrasing of real user questions: specific, sometimes oddly worded, often comparative (\"is X better than Y for oily skin\") rather than generic (\"why choose us\").",
      "Answers should be self-contained and directly useful without requiring the rest of the page for context — AI systems frequently lift just the FAQ answer text itself, not the surrounding page.",
      "A simple test: if you removed everything from the page except one FAQ question and answer, would it still make complete sense and honestly answer the question? If not, rewrite it.",
    ],
  },
  {
    slug: "grounded-agent-rag",
    title: "Grounding an agent in your own visibility data",
    excerpt: "How we built a chat agent that cites your prompt runs instead of hallucinating advice.",
    category: "Engineering",
    author: "Dev Malhotra",
    initials: "DM",
    date: "Apr 17, 2026",
    readTime: "10 min",
    thumb: "from-stone-50 via-orange-50 to-white",
    content: [
      "A chat interface that answers questions about your own visibility data is only useful if its answers are actually grounded in that data — not a generic, plausible-sounding response assembled from the model's general training.",
      "We built the Agent on retrieval-augmented generation (RAG): every question first triggers a search over your own stored visibility runs, citations, and content history, and only the relevant, real records are passed into the model's context before it responds.",
      "Practically, this means an answer like \"why did our visibility drop this week\" is backed by an actual query against your real run history, and the response cites specific numbers — \"based on 14 runs across ChatGPT and Perplexity this week\" — rather than a vague, ungrounded summary.",
      "This approach costs more engineering effort than a simple LLM wrapper, but it's the difference between an assistant you can trust for real decisions and one that just sounds confident.",
    ],
  },
];
