import type { Metadata } from "next";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and Conditions for using AnsarAEO.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="container-x prose prose-sm max-w-3xl py-32 md:py-40">
        <h1 className="text-3xl font-extrabold tracking-tight md:text-4xl">Terms & Conditions</h1>
        <p className="text-sm text-muted">Last updated: July 2026</p>

        <p>
          These Terms & Conditions (&quot;Terms&quot;) govern your access to and use of AnsarAEO
          (&quot;Service&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;), operated in India. By creating an
          account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.
        </p>

        <h2>1. Who Can Use AnsarAEO</h2>
        <p>
          You must be at least 18 years old and legally capable of entering into a binding contract under the
          Indian Contract Act, 1872, to use this Service. By signing up, you confirm this is true.
        </p>

        <h2>2. The Service</h2>
        <p>
          AnsarAEO tracks how AI engines (such as ChatGPT, Perplexity, and Gemini) mention your brand in response
          to tracked prompts, and provides tools to help improve that visibility. Results depend on third-party AI
          providers we do not control, and we do not guarantee any specific visibility outcome, ranking, or
          citation result.
        </p>

        <h2>3. Accounts</h2>
        <ul>
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You are responsible for all activity under your account.</li>
          <li>Notify us immediately at <a href="mailto:admin@ansaraeo.com">admin@ansaraeo.com</a> of any unauthorized use.</li>
        </ul>

        <h2>4. Subscription, Billing & Cancellation</h2>
        <ul>
          <li>Paid plans are billed in advance on a monthly or annual basis, as selected at checkout.</li>
          <li>You can cancel your subscription at any time from Settings &gt; Billing. Cancellation stops future
            billing; it does not automatically refund the current billing period unless required by our
            Refund Policy or applicable law.</li>
          <li>We do not use dark patterns to make cancellation difficult — see our commitment to transparent
            billing on the Pricing page.</li>
          <li>Prices are listed in INR (₹) for Indian customers and may be shown in other currencies for
            international customers.</li>
        </ul>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to track or generate content for unlawful, defamatory, or fraudulent purposes.</li>
          <li>Attempt to reverse-engineer, scrape, or resell the Service without written permission.</li>
          <li>Use automated means to exceed reasonable API/query rate limits.</li>
          <li>Publish AI-generated content produced via the Service without appropriate human review, where such
            content could mislead end users about its origin.</li>
        </ul>

        <h2>6. Content You Provide</h2>
        <p>
          You retain ownership of any content, brand information, and prompts you submit to the Service
          (&quot;Your Content&quot;). You grant us a limited license to process Your Content solely to provide and
          improve the Service.
        </p>

        <h2>7. AI-Generated Output</h2>
        <p>
          Content drafts, schema markup, and recommendations generated by the Service are AI-assisted and are
          provided &quot;as is&quot;, without warranty of accuracy or fitness for a particular purpose. You are
          responsible for reviewing and approving any AI-generated output before publishing it, in line with our
          in-product guidance.
        </p>

        <h2>8. Intellectual Property</h2>
        <p>
          The Service, including its software, design, and branding, is owned by us and protected by applicable
          intellectual property laws. These Terms do not grant you any rights to our trademarks or branding.
        </p>

        <h2>9. Termination</h2>
        <p>
          We may suspend or terminate accounts that violate these Terms, engage in abusive behavior, or fail to
          pay applicable fees, with notice where reasonably possible.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, AnsarAEO shall not be liable for indirect, incidental, or
          consequential damages arising from your use of the Service, including but not limited to loss of
          business, revenue, or data, or changes in third-party AI engine behavior outside our control.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive
          jurisdiction of the courts of India.
        </p>

        <h2>12. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the Service after changes take effect
          constitutes acceptance of the revised Terms.
        </p>

        <h2>13. Contact</h2>
        <p>
          Questions about these Terms? Email us at{" "}
          <a href="mailto:admin@ansaraeo.com">admin@ansaraeo.com</a>.
        </p>
      </main>
      <Footer />
    </>
  );
}
