import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import "@/workspace/workspaces";
import { get as getDescriptor, has } from "@/workspace/core";
import { createClient } from "@/lib/supabase/server";
import { EmptyStateCoach } from "@/workspace/primitives";

// ============================================================
// /dashboard/w/[kind] — per-kind object picker.
//
// Lists every object of `kind` the user can access (RLS-filtered by
// the cookie client) and links to /dashboard/w/[kind]/[slug]. Kept
// intentionally deterministic — no descriptor.list() hook yet, just
// a switch by kind against known tables. Adding a new kind requires
// one case here.
// ============================================================

export const dynamic = "force-dynamic";

type Item = { id: string; label: string; sublabel?: string };

// Per-kind coaching for the empty picker state — a one-liner that
// tells operators where to create the missing object.
function hintForKind(kind: string): string {
  switch (kind) {
    case "brand":
      return "Add a brand from the welcome flow to unlock every workspace.";
    case "prompt":
      return "Track prompts in the Prompts module — they seed every visibility scan.";
    case "competitor":
      return "Add competitors on the Competitors page to compare visibility side-by-side.";
    case "campaign":
      return "Launch a campaign to bundle related missions with a shared objective.";
    case "mission":
      return "Missions get created when opportunities are accepted or automations fire.";
    case "sprint":
      return "Group missions into a time-boxed sprint from the Sprints module.";
    case "engine":
      return "Engines seed automatically from active integrations — nothing to add.";
    case "content":
      return "Draft answers in Content Studio — every draft opens a workspace here.";
    case "opportunity":
      return "Opportunities are generated by the recommendations engine when data changes.";
    case "automation":
      return "Create an automation to react to engine events or opportunity types.";
    case "alert":
      return "Add an alert rule on the Alerts page to get notified when metrics move.";
    case "share":
      return "Generate a share link from any Report page — public snapshots for stakeholders.";
    case "task":
      return "Tasks get created when a mission decomposes or a playbook fires.";
    case "team":
      return "Create a team on the Members page to group operators around a set of brands.";
    case "playbook":
      return "Playbooks are org-scoped templates — create one on the Playbooks admin page.";
    case "integration":
      return "Connect GA4, Shopify, or Google Search Console on the brand's settings page.";
    case "site-audit":
      return "Run a site audit from the brand's Site Audit module — audits are immutable snapshots.";
    case "approval":
      return "Approvals are created when tasks or content items enter the deploy gate.";
    default:
      return `Add one from the ${kind} module first.`;
  }
}

function actionForKind(kind: string): { label: string; href: string } | undefined {
  switch (kind) {
    case "brand":
      return { label: "Add brand", href: "/dashboard/welcome" };
    case "prompt":
      return { label: "Manage prompts", href: "/dashboard/prompts" };
    case "competitor":
      return { label: "Manage competitors", href: "/dashboard/competitors" };
    case "campaign":
      return { label: "Launch campaign", href: "/dashboard/campaigns" };
    case "mission":
      return { label: "Open opportunities", href: "/dashboard/opportunities" };
    case "sprint":
      return { label: "Manage sprints", href: "/dashboard/sprints" };
    case "content":
      return { label: "Open Content Studio", href: "/dashboard/content" };
    case "opportunity":
      return { label: "Open queue", href: "/dashboard/opportunities" };
    case "automation":
      return { label: "Manage automations", href: "/dashboard/automations" };
    case "alert":
      return { label: "Manage alerts", href: "/dashboard/alerts" };
    case "share":
      return { label: "Open reports", href: "/dashboard/reports" };
    case "task":
      return { label: "Open task board", href: "/dashboard/tasks" };
    case "team":
      return { label: "Manage members", href: "/dashboard/settings/members" };
    case "integration":
      return { label: "Open integrations", href: "/dashboard/settings/integrations" };
    case "site-audit":
      return { label: "Open Site Audit", href: "/dashboard/site-audit" };
    case "approval":
      return { label: "Open Approvals", href: "/dashboard/approvals" };
    default:
      return undefined;
  }
}

async function loadItems(kind: string): Promise<Item[]> {
  const supabase = await createClient();
  if (kind === "brand") {
    const { data } = await supabase
      .from("brands")
      .select("id, name, slug, domain")
      .order("created_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; name: string; slug: string; domain: string | null }[] | null) ?? []).map(
      (b) => ({ id: b.slug, label: b.name, sublabel: b.domain ?? undefined }),
    );
  }
  if (kind === "prompt") {
    const { data } = await supabase
      .from("prompts")
      .select("id, text, language")
      .order("priority", { ascending: false })
      .limit(50);
    return ((data as { id: string; text: string; language: string }[] | null) ?? []).map((p) => ({
      id: p.id,
      label: p.text.length > 90 ? p.text.slice(0, 90) + "…" : p.text,
      sublabel: p.language?.toUpperCase(),
    }));
  }
  if (kind === "competitor") {
    const { data } = await supabase
      .from("competitors")
      .select("id, name, domain, confirmed")
      .eq("confirmed", true)
      .order("created_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; name: string; domain: string | null }[] | null) ?? []).map((c) => ({
      id: c.id,
      label: c.name,
      sublabel: c.domain ?? undefined,
    }));
  }
  if (kind === "campaign") {
    const { data } = await supabase
      .from("campaigns")
      .select("id, name, status, objective")
      .order("created_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; name: string; status: string; objective: string | null }[] | null) ?? []).map(
      (c) => ({ id: c.id, label: c.name, sublabel: `${c.status} · ${c.objective ?? "no objective"}` }),
    );
  }
  if (kind === "mission") {
    const { data } = await supabase
      .from("missions")
      .select("id, title, status, priority")
      .order("priority", { ascending: false })
      .order("updated_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; title: string; status: string; priority: number }[] | null) ?? []).map(
      (m) => ({ id: m.id, label: m.title, sublabel: `P${m.priority} · ${m.status.replace(/_/g, " ")}` }),
    );
  }
  if (kind === "sprint") {
    const { data } = await supabase
      .from("sprints")
      .select("id, name, status, goal, start_date, end_date")
      .order("start_date", { ascending: false, nullsFirst: false })
      .limit(50);
    return ((data as { id: string; name: string; status: string; goal: string | null; start_date: string | null; end_date: string | null }[] | null) ?? []).map(
      (s) => ({
        id: s.id,
        label: s.name,
        sublabel: `${s.status}${s.goal ? ` · ${s.goal}` : ""}`,
      }),
    );
  }
  if (kind === "engine") {
    const { data } = await supabase.from("engines").select("name, is_active").order("name");
    // Slug for engine is its name (chatgpt|perplexity|…), not a uuid.
    return ((data as { name: string; is_active: boolean }[] | null) ?? []).map((e) => ({
      id: e.name,
      label: e.name.replace(/_/g, " "),
      sublabel: e.is_active ? "active" : "disabled",
    }));
  }
  if (kind === "content") {
    const { data } = await supabase
      .from("content_items")
      .select("id, title, status, target_engine")
      .order("created_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; title: string | null; status: string; target_engine: string | null }[] | null) ?? []).map(
      (c) => ({
        id: c.id,
        label: c.title || "Untitled draft",
        sublabel: `${c.status}${c.target_engine ? ` · ${c.target_engine.replace(/_/g, " ")}` : ""}`,
      }),
    );
  }
  if (kind === "opportunity") {
    const { data } = await supabase
      .from("opportunity_recommendations")
      .select("id, title, type, status, priority_score")
      .neq("status", "dismissed")
      .order("priority_score", { ascending: false })
      .limit(50);
    return ((data as { id: string; title: string; type: string; status: string; priority_score: number | null }[] | null) ?? []).map(
      (o) => ({
        id: o.id,
        label: o.title,
        sublabel: `${o.status} · ${o.type.replace(/_/g, " ")} · ${Math.round((o.priority_score ?? 0) * 100)}%`,
      }),
    );
  }
  if (kind === "automation") {
    const { data } = await supabase
      .from("automations")
      .select("id, name, is_active")
      .order("updated_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; name: string; is_active: boolean }[] | null) ?? []).map((a) => ({
      id: a.id,
      label: a.name,
      sublabel: a.is_active ? "active" : "inactive",
    }));
  }
  if (kind === "alert") {
    const { data } = await supabase
      .from("geo_alert_rules")
      .select("id, metric, direction, window_type, is_active, threshold")
      .order("created_at", { ascending: false })
      .limit(50);
    return ((data as { id: string; metric: string; direction: string; window_type: string; is_active: boolean; threshold: number }[] | null) ?? []).map(
      (r) => ({
        id: r.id,
        label: r.metric.replace(/_/g, " "),
        sublabel: `${r.is_active ? "active" : "paused"} · ${r.direction} · ${r.window_type} · thr ${r.threshold}`,
      }),
    );
  }
  if (kind === "share") {
    const { data } = await supabase
      .from("share_view_tokens")
      .select("token, brand_id, expires_at, revoked, created_at")
      .order("created_at", { ascending: false })
      .limit(50);
    const rows = (data as { token: string; brand_id: string; expires_at: string; revoked: boolean; created_at: string }[] | null) ?? [];
    const brandIds = Array.from(new Set(rows.map((r) => r.brand_id)));
    const brandNames = new Map<string, string>();
    if (brandIds.length > 0) {
      const { data: bs } = await supabase
        .from("brands")
        .select("id, name")
        .in("id", brandIds);
      for (const b of (bs as { id: string; name: string }[] | null) ?? []) {
        brandNames.set(b.id, b.name);
      }
    }
    const now = Date.now();
    return rows.map((r) => {
      const brandName = brandNames.get(r.brand_id) ?? "brand";
      const expiresMs = new Date(r.expires_at).getTime();
      const state = r.revoked
        ? "revoked"
        : expiresMs < now
          ? "expired"
          : "live";
      return {
        id: r.token,
        label: `${brandName} · report link`,
        sublabel: state,
      };
    });
  }
  return [];
}

export default async function KindPicker({
  params,
}: {
  params: Promise<{ kind: string }>;
}) {
  const { kind } = await params;
  if (!has(kind)) notFound();
  const descriptor = getDescriptor(kind)!;
  // Descriptor-owned list() wins when defined — keeps picker query colocated
  // with the workspace. Fallback to the switch below for kinds not migrated.
  const items = descriptor.list ? await descriptor.list({ limit: 50 }) : await loadItems(kind);

  return (
    <div className="mx-auto max-w-3xl py-10">
      <p className="section-label">Workspace</p>
      <h1 className="mt-1 text-2xl font-bold tracking-tight text-ink capitalize">{kind}s</h1>
      <p className="mt-1 text-sm text-muted">
        Pick a {kind} to open its workspace — {descriptor.tabs.length} tabs each.
      </p>

      {items.length === 0 ? (
        <div className="mt-8">
          <EmptyStateCoach
            variant="coach"
            title={`No ${kind}s yet.`}
            description={hintForKind(kind)}
            action={actionForKind(kind)}
          />
        </div>
      ) : (
        <ul className="mt-6 space-y-2">
          {items.map((it) => (
            <li key={it.id}>
              <Link
                href={`/dashboard/w/${kind}/${it.id}/${descriptor.tabs[0]?.key ?? "overview"}`}
                className="group flex items-center justify-between rounded-2xl border border-line bg-white p-4 transition-colors hover:border-accent/40"
              >
                <div className="min-w-0">
                  <p className="truncate text-sm font-semibold text-ink group-hover:text-accent">
                    {it.label}
                  </p>
                  {it.sublabel && <p className="mt-0.5 truncate text-xs text-muted">{it.sublabel}</p>}
                </div>
                <ArrowRight className="h-4 w-4 text-muted transition-colors group-hover:text-accent" />
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
